name: $(Rev:r)
jobs:
- job: Build
  strategy:
    matrix:
      Windows:
        vmImage: 'windows-latest'
      Linux:
        vmImage: 'ubuntu-latest'
      MacOS:
        vmImage: 'macOS-latest'
  pool:
    vmImage: $(vmImage)
  variables:  
    BUILD_ID: $(BUILD.BUILDNUMBER)
    CI: true
    EQUINOX_INTEGRATION_SKIP_EVENTSTORE: true
    EQUINOX_INTEGRATION_SKIP_COSMOS: true
  steps:
  # exit code 8 signifies one or more assemblies did not have any non-skipped tests
  # CI env does not provide docker-compose simulated stores, which means most store tests are skipped
  - script: dotnet test -c Release --report-xunit-trx --ignore-exit-code 8 --results-directory tests/trx
    displayName: dotnet test
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: 'tests/trx/*.trx'
    condition: always()
  - script: dotnet build -c Release
    displayName: dotnet build
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'artifacts/nupkg'
      artifactName: 'nupkg'
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
