name: $(Rev:r)
jobs:
- job: Build
  strategy:
    matrix:
      Windows:
        vmImage: 'windows-latest'
      Linux:
        vmImage: 'ubuntu-latest'
      MacOS:
        vmImage: 'macOS-latest'
  pool:
    vmImage: $(vmImage)
  steps:
  - script: dotnet test --solution ./Equinox.sln --configuration Release --report-xunit-trx -v n
    displayName: dotnet test --solution ./Equinox.sln
    env:
      CI: true
      EQUINOX_INTEGRATION_SKIP_EVENTSTORE: true
      EQUINOX_INTEGRATION_SKIP_COSMOS: true
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: 'tests/**/*.trx'
    condition: always()
  - script: dotnet pack build.proj
    displayName: dotnet pack build.proj
    env:
      BUILD_ID: $(BUILD.BUILDNUMBER)
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'bin'
      artifactName: 'nupkgs'
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
