@startuml
!includeurl https://raw.githubusercontent.com/skleanthous/C4-PlantumlSkin/master/build/output/c4.puml

title Container diagram for Equinox.CosmosStore (+ Propulsion.Cosmos)
caption Moving parts for an Equinox app using a CosmosDB container that presently has 2 physical partitions

actor "Applications" <<External>> as apps

rectangle "Consistent Processing" <<Expanded>> {
    together {
        rectangle aggregate <<Component>> [
            Aggregate / Service

            Events: codec
            Fold: initial, fold
            interpret / decide
            snapshot / isOrigin
            Service
        ]
        rectangle stream <<Component>> [
            Equinox.Stream
        ]
    }

    database memorycache <<Internal>> [
        **System.MemoryCache**
        StreamName ->
        etag+version+state
    ]

    rectangle eqxcosmos <<Component>> [
        Equinox.CosmosStore
    ]

    cloud "CosmosDB Database D" as db {
        rectangle "Container C" as cosmos <<Container>> {
            node "D\C\Range 0" {
                rectangle [Sync SP] as sync0 <<Internal>>
                database range0 <<Internal>> [
                    **Range0**
                    RangeA-M Tip Documents
                    RangeA-M Stream Events
                ]
            }
            node "D\C\Range 1" {
                rectangle [Sync SP] as sync1 <<Internal>>
                database range1 <<Internal>> [
                    **Range1**
                    RangeN-Z Tip Documents
                    RangeN-Z Stream Events
                ]
            } 
        }
    }
}

rectangle "**Publishers**" as publishers <<External Container>> {
    rectangle cfp0 <<External Component>> [
        **ChangeFeedProcessor A**
    ]
    rectangle projector <<External Component>> [
        **Publisher**
    ]
}

rectangle "**Reactors**" as reactors <<External Container>> {
    rectangle cfp1 <<External Component>> [
        **ChangeFeedProcessor B**
    ]
    rectangle reactor <<External Component>> [
        **Reactor**
    ]
}
database caches <<External>> [
    **Read Models**
]

rectangle outputs <<External System>> [
    **Output Feeds**

    Topics / ATOM
]

database aux <<External>> [
    **Aux CosmosDB**
    CheckpointA0 CheckpointA1
    CheckpointB0 CheckpointB1
    HostALease0 HostALease1
    HostBLease0 HostBLease1
]

apps      <->   aggregate   : transact\nagainst
apps      <.    caches      : reference\neventually\nconsistent

aggregate <-L-> stream      : Transact/\nQuery
stream     -L-> eqxcosmos   : Load/\nTrySync

eqxcosmos <-L-> memorycache : TryGet/\nUpdate
eqxcosmos <->   sync0       : ExecuteStoredProc\n[Azure.Cosmos TCP]
eqxcosmos <->   cosmos      : ReadItem/\nQueryDocuments\n[Azure.Cosmos TCP]
eqxcosmos <->   sync1       : ExecuteStoredProc\n[Azure.Cosmos TCP]

range0     ..>  cfp0        : continuously queries
range1     ..>  cfp0        : continuously queries

range0     ..>  cfp1        : continuously queries
range1     ..>  cfp1        : continuously queries

cfp0      <->   aux         : keeps checkpoints in\nnegotiates leases via
cfp1      <->   aux         : keeps checkpoints in\nnegotiates leases via
cfp0      <.>   publishers  : projects events
cfp1      <.>   reactors    : tracks relevant events
reactors    .>  caches      : maintains views in
reactors    .>  publishers  : compose notificatons for
projector   .>  outputs     : emits to

eqxcosmos -[hidden]D-> sync0
cfp0      -[hidden]D-> aux
publishers-[hidden]D-> outputs
reactors  -[hidden]U-> caches
caches    -[hidden]U-> apps

@enduml